title: HOLA PROJECT Facundo Gonzalez
description: Documentaci칩n del hola project de Facundo Gonzalez y muy poquito I침aki Gongora, la nai no ayudo solo molesto guacalote
theme: jekyll-theme-cayman

# Configuraci칩n importante para Jekyll
defaults:
  -
    scope:
      path: "" # aplica a todos los archivos
    values:
      layout: default

# Especificar que los archivos .md deben ser procesados
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configurar la p치gina principal
index_page: index.md 
